# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a9c25ff216022c13daf5e074718169ced46d0023bfeae7a45a8ca40dc279462648b5da347c5853a70004c79ba365c9144f8fa19c514f948e52afb1fdc2652ce

test:
  secret_key_base: 9dea845ef9b05927a6dfb4f00e6dd729362f68f5c088ff6e77aa4a92f667fadee66c49a85ad53dcdc2a32c1578363726c69ed34ecd5a677a07192eae63919b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
